name: Deploy to Development and Demo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "built and tested"

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: dev
    steps:
      - run: echo "deployed to dev"

  deploy-to-demo:
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment:
      name: demo
    steps:
      - run: echo "deployed to demo"
