name: Deploy to Development and Demo

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - "!release-please**"
    types:
      - closed

jobs:
  build-and-test:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "built and tested"

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: dev
    steps:
      - run: echo "deployed to dev"

  deploy-to-demo:
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment:
      name: demo
    steps:
      - run: echo "deployed to demo"
